fn main() {
    let mut zip = simzip::ZipInfo::new_with_comment(
        "test.zip",
        "Generated by WebFolder (Java nio) 1.9.155, Copyright (c) 2009, 2026 by Dmitriy Rogatkin",
    );
    zip.add(simzip::ZipEntry::new(
        ".gitignore",
        r#"src/test
test.zip"#
            .as_bytes()
            .to_vec(),
    ));
    let _ = zip.add(simzip::ZipEntry::new(
        "test entryΘ.txt",
        "test content".as_bytes().to_vec(),
    ));
    zip.add(simzip::ZipEntry::from_file("README.md", Some("doc")));
    #[cfg(feature = "test_unix")]
    {
        zip.add(simzip::ZipEntry::from_file("run script.sh", Some("test")));
        zip.add(simzip::ZipEntry::from_file(
            "read only.txt",
            Some(&"test".to_string()),
        ));
    }
    match zip.store() {
        Ok(()) => println! {"Zipped good!"},
        Err(msg) => println! {"zip error: {msg}"},
    }
}
